### ISSUE TITLE
Some information

### ISSUE THREAD

**Issue by Angelk90** [react-navigation/material-bottom-tabs#11]
@satya164 , @brentvatne , 

Hi, reading the documentation I could not answer some questions so I ask here:

1) Is it possible to change the color of the ripple effect?
It is seen in dark color, as in the image:
![russia_fifa_2018](https://reactnavigation.org/docs/assets/navigators/bottom-navigation.gif)

If yes, how?
2) In the documentation there is written tabcolor:
https://reactnavigation.org/docs/en/material-bottom-tab-navigator.html#tabbarcolor

Would it be possible to do something like this?
With the label that remains?
![](https://raw.githubusercontent.com/timomeh/react-native-material-bottom-navigation/master/.github/demo-full.gif)

3) Would it be possible to give an example, in which a tab has a badges?

**Comment by rodgomesc** [comment]
@Angelk90 , Unfortunately I can not help you, but maybe you can help me hahaha, were you able to change the font size using this lib? 

[Issue change Label Font Size ](https://github.com/react-navigation/react-navigation-material-bottom-tabs/issues/10)

**Comment by satya164** [comment]
1. Ripple color cannot be changes. It's automatic based on tab bar's background color
2. `shifting: false`
3. `tabBarBadge: 2` in `navigationOptions`
