### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by tomzaku** [react-navigation/material-bottom-tabs#12]
Is there any plan about supporting typescript?

**Comment by rebirthtobi** [comment]
Any response to the typescript support, having issues here

**Comment by iRoachie** [comment]
Hey I added the typings on definitely typed. You can install using 
```
npm install --save @types/react-navigation-material-bottom-tabs
```

**Comment by satya164** [comment]
The library is now written in TS and has TypeScript support.
