### ISSUE TITLE
Screen Blinking/Flashing on tab change

### ISSUE THREAD

**Issue by magworkss** [react-navigation/material-bottom-tabs#19]
Hello 

After replace
`import { createBottomTabNavigator } from 'react-navigation';` to 
`import { createMaterialBottomTabNavigator } from 'react-navigation-material-bottom-tabs';`
every time when on tab change event works my screen is flashing/blinking

[**Snack**](https://snack.expo.io/@avo/reactnavigation-issue)
https://snack.expo.io/@avo/reactnavigation-issue
@brentvatne 
Is there any solution ?

**Comment by Drazail** [comment]
@satya164

Any suggestions?

**Comment by satya164** [comment]
@Drazail see https://github.com/callstack/react-native-paper/issues/516#issuecomment-417412597

**Comment by Drazail** [comment]
@satya164

That doesn't help, I think it has something to do with transition animation.

**Comment by satya164** [comment]
Please share your code

**Comment by Ghost-Luu** [comment]
Same question

**Comment by ZeroCool00** [comment]
Any solution? Its happening in latest version too. (3.3.0)

**Comment by formatlos** [comment]
I do have the same issues

**Comment by mikebouwmans** [comment]
I have the same issue aswell.

**Comment by DannyHinshaw** [comment]
Same issue, using in combination with `SwitchNavigator` which doesn't seem to have the `stackNavigatorConfig.cardStyle.backgroundColor` prop (which may fix it) that's available on `StackNavigator`.

**Comment by toby-pondr** [comment]
I had this same issue when I put Stack Navigators inside a Tab Navigator. Instead, I reversed that logic. I created my Tab Navigator first and added that as a sole screen to a Stack Navigator.

See this link. It shows a Tab Navigator nested inside a Stack Navigator.
https://reactnavigation.org/docs/en/navigation-options-resolution.html#a-stack-contains-a-tab-navigator-and-you-want-to-set-the-title-on-the-stack-header

**Comment by kolohelios** [comment]
From what I'm seeing, it has something to do with SafeAreaView. When I remove it, I no longer get the flashing. I still need to do further investigation.

**Comment by kelkmere** [comment]
@kolohelios Yes the issue is gone when I removed SafeAreaView.

**Comment by satya164** [comment]
You can pass `sceneAnimationEnabled: false` to disable animation when switching tabs.
