### ISSUE TITLE
Tab Focus Issue on First App launch

### ISSUE THREAD

**Issue by victorkvarghese** [react-navigation/material-bottom-tabs#22]
```
import React from 'react';
import { createMaterialBottomTabNavigator } from 'react-navigation-material-bottom-tabs';
import { createStackNavigator } from 'react-navigation';
import Home from 'app/screens/Home';
import Business from 'app/screens/Business';
import News from 'app/screens/News';
import Offers from 'app/screens/Offers';
import TabIcon from 'app/components/TabIcon';

import BusinessSubScreen from 'app/screens/BusinessSubScreen';
import BusinessDetail from 'app/screens/BusinessDetail';

const HomeTabIcon = ({ tintColor }) => (
    <TabIcon name="home" tintColor={tintColor} />
);
const BusinessTabIcon = ({ tintColor }) => (
    <TabIcon name="business" tintColor={tintColor} />
);
const NewsTabIcon = ({ tintColor }) => (
    <TabIcon name="public" tintColor={tintColor} />
);
const OffersTabIcon = ({ tintColor }) => (
    <TabIcon name="loyalty" tintColor={tintColor} />
);

const BusinessStack = createStackNavigator({
    Business: {
        screen: Business,
        navigationOptions: { header: null }
    },
    BusinessSubScreen: {
        screen: BusinessSubScreen,
        navigationOptions: { header: null }
    }
});

const BottomNavigation = createMaterialBottomTabNavigator(
    {
        Home: {
            screen: Home,
            navigationOptions: { tabBarIcon: HomeTabIcon }
        },
        Business: {
            screen: BusinessStack,
            navigationOptions: { tabBarIcon: BusinessTabIcon }
        },
        News: {
            screen: News,
            navigationOptions: { tabBarIcon: NewsTabIcon }
        },
        Offers: {
            screen: Offers,
            navigationOptions: { tabBarIcon: OffersTabIcon }
        }
    },
    {
        initialRouteName: 'Home',
        activeColor: '#C2202D',
        inactiveColor: '#95a5a6',
        barStyle: { backgroundColor: '#FFFFFF' }
    }
);

const MyApp = createStackNavigator(
    {
        BottomNavigation: {
            screen: BottomNavigation,
            navigationOptions: { header: null }
        },
        BusinessDetail: {
            screen: BusinessDetail,
            navigationOptions: { header: null }
        }
    },
    { initialRouteName: 'BottomNavigation' }
);

export default MyApp;
```

```
import React, { Component } from 'react';
import Icon from 'react-native-vector-icons/MaterialIcons';

import PropTypes from 'prop-types';

export default class TabIcon extends Component {
    render() {
        const { name, tintColor, style } = this.props;

        return (
            <Icon
                style={style ? style : {}}
                name={name}
                size={24}
                color={tintColor}
            />
        );
    }
}
TabIcon.propTypes = {
    name: PropTypes.string,
    tintColor: PropTypes.string,
    style: PropTypes.object,
    type: PropTypes.string
};

```
**When app launches**
![screenshot_20180925-162349__01](https://user-images.githubusercontent.com/15869386/46010215-7e0fba00-c0df-11e8-97bd-89c294921562.jpg)

**When we select another tab for first time**

![screenshot_20180925-160532__02](https://user-images.githubusercontent.com/15869386/46010223-81a34100-c0df-11e8-8b2c-eb2ec3f65060.jpg)

**Comment by JustPilz** [comment]
same problem

**Comment by alexandrius** [comment]
I have this problem too

**Comment by chijuiwu** [comment]
same here

**Comment by rendy14s** [comment]
same here

**Comment by brentvatne** [comment]
what react-native version are you all using?

**Comment by victorkvarghese** [comment]
@brentvatne I got this issue on 0.55.4 and 0.57.1

**Comment by alexandrius** [comment]
@brentvatne 0.57.2

**Comment by brentvatne** [comment]
interesting - I opened a PR on react-native-paper that fixes this

**Comment by satya164** [comment]
yeah, I haven't tested on 0.57, but I couldn't repro on .55

**Comment by rendy14s** [comment]
Hi @satya164, @brentvatne  i have update react-native-paper to `"react-native-paper": "^2.2.2"` , and i still get like this, for the first app lunch ?

![image](https://user-images.githubusercontent.com/10143804/48112579-9d2a6b80-e289-11e8-8224-23327d0c6f56.png)

**Comment by brentvatne** [comment]
2.2.3

**Comment by rendy14s** [comment]
Hi @brentvatne Ok i will up to 2.2.3 thank you

**Comment by rendy14s** [comment]
@victorkvarghese hi, you solved about this? because i not haha

**Comment by victorkvarghese** [comment]
@rendy14s ..update to the latest version .. it should work .. I haven't had a chance to test this yet

**Comment by rendy14s** [comment]
i have do that. to the version 2.2.3 and today i'am using `npm outdated` , and now paper have latest version `2.2.4` and i update. and still not work. :D

**Comment by Caundy** [comment]
+1 Experiencing the same issue with react-native 0.57.0 and react-native-paper 2.2.4

**Comment by Caundy** [comment]
Could this be linked to the version of this package? 
Any chance you could tell me in which configuration of:
    react-native v0.57.0 + react-native-paper v2.2.4 + react-navigation-material-bottom-tabs vX.Y.Z 
it works on your side?

**Comment by brentvatne** [comment]
@caundy - it would be best if you could post a reproducible example

**Comment by Caundy** [comment]
@brentvatne  Can't do so at the moment. Still, would simply like to know whether the version of this library could affect that behaviour and on which versions has the fix been tested to be able to check it on my side

**Comment by satya164** [comment]
You need `react-navigation-material-bottom-tabs@0.4.0` and `react-native-paper@2.2.4`

**Comment by rendy14s** [comment]
Same with me @satya164 

![screenshot_2018-11-13-21-35-44-69](https://user-images.githubusercontent.com/10143804/48420355-cf0d6780-e78c-11e8-8b20-fc37ed972bc7.png)

**Comment by Caundy** [comment]
@satya164 Thank you for responding :) 
Increasing the rn-navigation-material-bottom-tabs to 0.4.0 indeed resolved the previously mentioned issue but... reverted it - now after opening the app on first click none of the tabs are highlighted as active. Any chance you encountered it and know how to resolve it?
