### ISSUE TITLE
Unable to resolve module 'module://@react-navigation/core.js' with react-navigation 3.0

### ISSUE THREAD

**Issue by hot0ES** [react-navigation/material-bottom-tabs#32]
Hello.

You can find an snack with the error [here](https://snack.expo.io/@hotes/react-navigation-3.0.x)

Thank you.

**Comment by jjeffrin** [comment]
Where you able to find a solution to this problem? I'm also having the same issue.

**Comment by fzoff** [comment]
I was able to resolve this issue by manually adding this line to the package.json file 
"@react-navigation/core": "3.2.1"

**Comment by jjeffrin** [comment]
Will update you after trying this!

**Comment by satya164** [comment]
Closing since this is an old issue. Please open a new issue if you are still facing problems.
