### ISSUE TITLE
Bottom bar with a fab like in Android material app bar bottom

### ISSUE THREAD

**Issue by nareshkatta99** [react-navigation/material-bottom-tabs#42]
How to make bottom tab navigation with fab in the center like in [Android App bars: bottom](https://material.io/design/components/app-bars-bottom.html#anatomy)

**Comment by satya164** [comment]
This is Bottom Navigation library, not app bar.

For app bar cutout, you can use an image https://snack.expo.io/@satya164/material-design-cutout
