### ISSUE TITLE
Tabs flash when closing keyboard on Tab-disabled screen

### ISSUE THREAD

**Issue by FoxInFlame** [react-navigation/material-bottom-tabs#43]
For some screens within my app, I have disabled the tab bar's visibility, by checking the `routeName` and setting `tabBarVisible: false` in my react-navigation navigationOptions.

When a keyboard is closed for a TexInput within such screen, the bottom tab flashes very quickly before disappearing as it should.

Demo:
![Demo](https://i.imgur.com/8mzDawb.gif)

**Comment by satya164** [comment]
Can you provide full repro please?

**Comment by FoxInFlame** [comment]
@satya164 Sure thing! https://snack.expo.io/@foxinflame/627848

**Comment by ZChenzy** [comment]
Any update or work around on this?

**Comment by cod3hunter** [comment]
+1

**Comment by carlmagumpara** [comment]
same issue here

**Comment by N-Dimitri** [comment]
+1

**Comment by N-Dimitri** [comment]
Is very strange,
I add 
 keyboardHidesNavigationBar={false} in MaterialBottomTabView.tsx fix it

`     <BottomNavigation
        // Pass these for backward compaibility
        {...rest}
        activeColor={activeColor}
        inactiveColor={inactiveColor}
        renderIcon={this._renderIcon}
        barStyle={[barStyle, extraStyle]}
        keyboardHidesNavigationBar={false}
        navigationState={navigation.state}
        getColor={this._getColor}
      />`
