### ISSUE TITLE
It's not apply activeColor in text

### ISSUE THREAD

**Issue by erbud** [react-navigation/material-bottom-tabs#49]
With:

• react-native 0.59.8
• react-navigation 3.11.1

The `activeColor` property no apply in the Tab text (Android).

Regards,

**Comment by sospedra** [comment]
Same problem here. What I found is that the if/else condition I believe is wrong: https://github.com/react-navigation/material-bottom-tabs/blob/master/src/navigators/createMaterialBottomTabNavigator.js#L44

For now @erbud you can use: `activeTintColorLight` and `inactiveTintColorLight`
If any moderator can confirm my assumption I could work in a fix PR.

Hope it helps

**Comment by erbud** [comment]
All right. Thx bro!

**Comment by binzip** [comment]
I was struggling with color apply on my Icon.
<code>activeTinitColor</code>, <code>inactiveTintColor</code> works. Thx!
