### ISSUE TITLE
Background Colour not working

### ISSUE THREAD

**Issue by erdarshandoshi** [react-navigation/material-bottom-tabs#55]
Hi,

I am designing tabs using this package and below is my code
There are 2 tabs in my page. I want to give BACKGROUND COLOR to one of the tabs when it is active, but when i give "tabBarColor" property it is giving background color to entire tab and not on selected tab. Can i give different backgroundcolor specific to one tab when it is active.

export const MaterialBottomTabNavigator = createMaterialBottomTabNavigator(
  {
    Vendors: {
      screen: HomeScreen,
      navigationOptions: { tabBarColor: '#E72E77', inactiveColor: '#000' },
    },
    Checklist: {
      screen: Checklist,
      navigationOptions: { tabBarColor: '#fff', inactiveColor: '#000' },
    },
  },
  {
    shifting: true,
    activeColor: '#000',
    inactiveColor: '#fff',
    barStyle: { backgroundColor: 'red' },
  },
);

**Comment by satya164** [comment]
Fixed in https://github.com/react-navigation/material-bottom-tabs/commit/807d80ecf7544c2a6d1205d798a478dd76c14658

**Comment by erdarshandoshi** [comment]
Please provide me details how will i pass active color to this ?
