### ISSUE TITLE
Can't import {MaterialCommunityIcons} from 'react-native-vector-icons';

### ISSUE THREAD

**Issue by ilibilibom** [react-navigation/material-bottom-tabs#61]
I'm trying to import  {MaterialCommunityIcons} from 'react-native-vector-icons' 
and vscode is telling me:
```
Module '"../../../../../../../../../Users/ilandiamond/Developer/Code/me/bla/app/node_modules/@types/react-native-vector-icons"' has no exported member 'MaterialCommunityIcons'
```

**Comment by satya164** [comment]
You're probably using TypeScript and haven't installed the definitions. Regardless, the package is not part of the repo so please open issue reports for it in `react-native-vector-icon`'s repo. We have limited bandwidth and can only help with bug reports in React Navigation.

**Comment by ilibilibom** [comment]
I am using TS, thanks.
