### ISSUE TITLE
Badges 

### ISSUE THREAD

**Issue by divdotshoya** [react-navigation/material-bottom-tabs#8]
Hey there!
Is there any plan to implement Badges in a convenient way for the tabs as per the Material Design specs?
https://material.io/design/components/bottom-navigation.html#behavior
![image](https://user-images.githubusercontent.com/39280494/41880246-e0b15236-7891-11e8-9edd-30d77381183a.png)
If not yet planned, would like to request it be implemented at some point.
Thanks for all your work!

**Comment by jstansbe** [comment]
Not really a material badge... but its something!

Looking at the BottomNavigation.js file, there is a styles.iconContainer with a width and height hard coded. I had to bump those up so I could make enough room too display my badge.

**Comment by satya164** [comment]
It's planned: https://github.com/callstack/react-native-paper/issues/288#issuecomment-401088556

**Comment by dsznajder** [comment]
@satya164 Any due date on that feature? Is it planned for 2.0.0 or just as a standalone feature? I have some scratch on that for `BottomNavigation` but not sure if contribution needed :)

**Comment by satya164** [comment]
This feature is now added in React Native Paper. Would be great if someone could send a PR using it here :)

**Comment by satya164** [comment]
9dcb29b35d077440550dfa08c1ac8b0ce11fd710
